#SOURCES
sources:
  - name: source_csv
    type: file
    format: csv
    path: ./data/client1.csv

  - name: source_json
    type: file
    format: json
    path: ./data/users.json

  - name: source_xml
    type: file
    format: xml
    path: ./data/book.xml

  - name: source_api
    type: api
    url: "https://jsonplaceholder.typicode.com/todos"

  - name: source_mysql
    type: database
    connection_params:
      host: "localhost"
      user: "root"
      password: ""
      database: "dm22"
    query: "SELECT * FROM membres"


# TRANSFORMATION
transformations:

# Transformation pour source_csv

  - source: source_csv
    type: merge_data
    with: "./data/client2.csv"
    common_column: "identifiant"

  - source: source_csv
    type: handle_missing_values

  - source: source_csv
    type: filter
    condition: 'genre == "M"'

  - source: source_csv
    type: add_attribute
    attribute_name: salaire
    attribute_value: '250'

  - source: source_csv
    type: perform_calculation
    calculation: salaire * 15

  - source: source_csv
    type: normalize_data



# Transformation pour source_json
  - source: source_json
    type: clean_balance
    balance: "balance"

  - source: source_json
    type: handle_missing_values

  - source: source_json
    type: filter
    condition: age < 34

  - source: source_json
    type: add_attribute
    attribute_name: "ville"
    attribute_value: "san francisco"

  - source: source_json
    type: normalize_data


# Transformation pour source_xml
  - source: source_xml
    type: filter
    condition: Price <= 20

  - source: source_xml
    type: handle_missing_values

  - source: source_xml
    type: add_attribute
    attribute_name: "color"
    attribute_value: "red, white, blue"

  - source: source_xml
    type: normalize_data


# Transformation pour source_api
  - source: source_api
    type: normalize_data


# Transformation pour source_mysql
  - source: source_mysql
    type: normalize_data

  - source: source_mysql
    type: drop_missing_values_from_database
    connection_params:
      host: 'localhost'
      user: 'root'
      password: ''
      database: 'dm22'
    table_name: 'membres'
    column_names: 'email'

  - source: source_mysql
    type: filter_data_from_database
    connection_params:
      host: 'localhost'
      user: 'root'
      password: ''
      database: 'dm22'
    table_name: 'membres'
    condition: "ville = 6"


#DESTINATION

destinations:

  # Destination pour source_database
  - source: source_mysql
    destination: mysql
    connection_params:
       host: 'localhost'
       user: 'root'
       password: ''
       database: 'dm22'
    table_name: update_membres
    file_path: table_name


  #Destination pour source_csv
  - source: source_csv
    destination: csv
    file_path: "./destination/finale_client.csv"

   #Destination pour source_json
  - source: source_json
    destination: json
    file_path: "./destination/finale_user.json"

   #Destination pour source_xml
  - source: source_xml
    destination: xml
    file_path: "./destination/finale_book.xml"


   #Destination pour source_api
  - source: source_api
    destination: json
    file_path: "./destination/finale_api.json"