#SOURCES
sources:
  - name: source_csv
    type: file
    format: csv
    path: ./data/client1.csv

  - name: source_json
    type: file
    format: json
    path: ./data/users.json

  - name: source_xml
    type: file
    format: xml
    path: ./data/book.xml

 # - name: source_api
 #   type: api
 #   url: https://dummyjson.com/users


# TRANSFORMATION
transformations:
# Transformation pour source_csv

  - source: source_csv
    type: merge_data
    with: './data/client2.csv'
    on: genre

  - source: source_csv
    type: filter
    condition: 'genre == "M"'



  - source: source_csv
    type: add_attribute
    attribute_name: salaire
    attribute_value: 250

  - source: source_csv
    type: perform_calculation
    calculation: salaire * 15

  - source: source_csv
    type: normalize_data

  - source: source_csv
    type: handle_missing_values



# Transformation pour source_json
  - source: source_json
    type: clean_balance
    balance: "balance"

  - source: source_json
    type: handle_missing_values

  - source: source_json
    type: filter
    condition: age < 34

  - source: source_json
    type: add_attribute
    attribute_name: "ville"
    attribute_value: "san francisco"

  - source: source_json
    type: normalize_data


# Transformation pour source_xml
  - source: source_xml
    type: filter
    condition: Price <= 20

  - source: source_xml
    type: handle_missing_values

  - source: source_xml
    type: add_attribute
    attribute_name: "color"
    attribute_value: "red, white, blue"

  - source: source_xml
    type: normalize_data


#DESTINATION
destinations:
  # Destination pour source_database
  ###- source: source_database
    #destination: database
    #table_name: "output_table_1"
    #connection_string: "your_database_connection_string"

   #Destination pour source_csv
  - source: source_csv
    destination: csv
    file_path: "./destination/output_2.csv"

   #Destination pour source_json
  - source: source_json
    destination: json
    file_path: "./destination/fichier.json"

   #Destination pour source_xml
  - source: source_xml
    destination: xml
    file_path: "./destination/fichier.xml"


   #Destination pour source_api
 # - source: source_api
 #   destination: json
 #   file_path: "./destination/fichier_api.json"